/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dwi.demo.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Location extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4337649148856387740L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Location\",\"namespace\":\"de.dwi.demo.avro.model\",\"fields\":[{\"name\":\"gpsX\",\"type\":\"long\"},{\"name\":\"gpsY\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Location> ENCODER =
      new BinaryMessageEncoder<Location>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Location> DECODER =
      new BinaryMessageDecoder<Location>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Location> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Location> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Location>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Location to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Location from a ByteBuffer. */
  public static Location fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long gpsX;
  @Deprecated public long gpsY;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Location() {}

  /**
   * All-args constructor.
   * @param gpsX The new value for gpsX
   * @param gpsY The new value for gpsY
   */
  public Location(java.lang.Long gpsX, java.lang.Long gpsY) {
    this.gpsX = gpsX;
    this.gpsY = gpsY;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gpsX;
    case 1: return gpsY;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gpsX = (java.lang.Long)value$; break;
    case 1: gpsY = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'gpsX' field.
   * @return The value of the 'gpsX' field.
   */
  public java.lang.Long getGpsX() {
    return gpsX;
  }

  /**
   * Sets the value of the 'gpsX' field.
   * @param value the value to set.
   */
  public void setGpsX(java.lang.Long value) {
    this.gpsX = value;
  }

  /**
   * Gets the value of the 'gpsY' field.
   * @return The value of the 'gpsY' field.
   */
  public java.lang.Long getGpsY() {
    return gpsY;
  }

  /**
   * Sets the value of the 'gpsY' field.
   * @param value the value to set.
   */
  public void setGpsY(java.lang.Long value) {
    this.gpsY = value;
  }

  /**
   * Creates a new Location RecordBuilder.
   * @return A new Location RecordBuilder
   */
  public static de.dwi.demo.avro.model.Location.Builder newBuilder() {
    return new de.dwi.demo.avro.model.Location.Builder();
  }

  /**
   * Creates a new Location RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Location RecordBuilder
   */
  public static de.dwi.demo.avro.model.Location.Builder newBuilder(de.dwi.demo.avro.model.Location.Builder other) {
    return new de.dwi.demo.avro.model.Location.Builder(other);
  }

  /**
   * Creates a new Location RecordBuilder by copying an existing Location instance.
   * @param other The existing instance to copy.
   * @return A new Location RecordBuilder
   */
  public static de.dwi.demo.avro.model.Location.Builder newBuilder(de.dwi.demo.avro.model.Location other) {
    return new de.dwi.demo.avro.model.Location.Builder(other);
  }

  /**
   * RecordBuilder for Location instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Location>
    implements org.apache.avro.data.RecordBuilder<Location> {

    private long gpsX;
    private long gpsY;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.dwi.demo.avro.model.Location.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gpsX)) {
        this.gpsX = data().deepCopy(fields()[0].schema(), other.gpsX);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.gpsY)) {
        this.gpsY = data().deepCopy(fields()[1].schema(), other.gpsY);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Location instance
     * @param other The existing instance to copy.
     */
    private Builder(de.dwi.demo.avro.model.Location other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.gpsX)) {
        this.gpsX = data().deepCopy(fields()[0].schema(), other.gpsX);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.gpsY)) {
        this.gpsY = data().deepCopy(fields()[1].schema(), other.gpsY);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'gpsX' field.
      * @return The value.
      */
    public java.lang.Long getGpsX() {
      return gpsX;
    }

    /**
      * Sets the value of the 'gpsX' field.
      * @param value The value of 'gpsX'.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.Location.Builder setGpsX(long value) {
      validate(fields()[0], value);
      this.gpsX = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gpsX' field has been set.
      * @return True if the 'gpsX' field has been set, false otherwise.
      */
    public boolean hasGpsX() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'gpsX' field.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.Location.Builder clearGpsX() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'gpsY' field.
      * @return The value.
      */
    public java.lang.Long getGpsY() {
      return gpsY;
    }

    /**
      * Sets the value of the 'gpsY' field.
      * @param value The value of 'gpsY'.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.Location.Builder setGpsY(long value) {
      validate(fields()[1], value);
      this.gpsY = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'gpsY' field has been set.
      * @return True if the 'gpsY' field has been set, false otherwise.
      */
    public boolean hasGpsY() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'gpsY' field.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.Location.Builder clearGpsY() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Location build() {
      try {
        Location record = new Location();
        record.gpsX = fieldSetFlags()[0] ? this.gpsX : (java.lang.Long) defaultValue(fields()[0]);
        record.gpsY = fieldSetFlags()[1] ? this.gpsY : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Location>
    WRITER$ = (org.apache.avro.io.DatumWriter<Location>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Location>
    READER$ = (org.apache.avro.io.DatumReader<Location>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
