/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dwi.demo.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class NetPoint extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4008427540016189299L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NetPoint\",\"namespace\":\"de.dwi.demo.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"location\",\"type\":{\"type\":\"record\",\"name\":\"Location\",\"fields\":[{\"name\":\"gpsX\",\"type\":\"long\"},{\"name\":\"gpsY\",\"type\":\"long\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NetPoint> ENCODER =
      new BinaryMessageEncoder<NetPoint>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NetPoint> DECODER =
      new BinaryMessageDecoder<NetPoint>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<NetPoint> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<NetPoint> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NetPoint>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this NetPoint to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a NetPoint from a ByteBuffer. */
  public static NetPoint fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String id;
  @Deprecated public de.dwi.demo.avro.model.Location location;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NetPoint() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param location The new value for location
   */
  public NetPoint(java.lang.String id, de.dwi.demo.avro.model.Location location) {
    this.id = id;
    this.location = location;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return location;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: location = (de.dwi.demo.avro.model.Location)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public de.dwi.demo.avro.model.Location getLocation() {
    return location;
  }

  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(de.dwi.demo.avro.model.Location value) {
    this.location = value;
  }

  /**
   * Creates a new NetPoint RecordBuilder.
   * @return A new NetPoint RecordBuilder
   */
  public static de.dwi.demo.avro.model.NetPoint.Builder newBuilder() {
    return new de.dwi.demo.avro.model.NetPoint.Builder();
  }

  /**
   * Creates a new NetPoint RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NetPoint RecordBuilder
   */
  public static de.dwi.demo.avro.model.NetPoint.Builder newBuilder(de.dwi.demo.avro.model.NetPoint.Builder other) {
    return new de.dwi.demo.avro.model.NetPoint.Builder(other);
  }

  /**
   * Creates a new NetPoint RecordBuilder by copying an existing NetPoint instance.
   * @param other The existing instance to copy.
   * @return A new NetPoint RecordBuilder
   */
  public static de.dwi.demo.avro.model.NetPoint.Builder newBuilder(de.dwi.demo.avro.model.NetPoint other) {
    return new de.dwi.demo.avro.model.NetPoint.Builder(other);
  }

  /**
   * RecordBuilder for NetPoint instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NetPoint>
    implements org.apache.avro.data.RecordBuilder<NetPoint> {

    private java.lang.String id;
    private de.dwi.demo.avro.model.Location location;
    private de.dwi.demo.avro.model.Location.Builder locationBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.dwi.demo.avro.model.NetPoint.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.location)) {
        this.location = data().deepCopy(fields()[1].schema(), other.location);
        fieldSetFlags()[1] = true;
      }
      if (other.hasLocationBuilder()) {
        this.locationBuilder = de.dwi.demo.avro.model.Location.newBuilder(other.getLocationBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing NetPoint instance
     * @param other The existing instance to copy.
     */
    private Builder(de.dwi.demo.avro.model.NetPoint other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.location)) {
        this.location = data().deepCopy(fields()[1].schema(), other.location);
        fieldSetFlags()[1] = true;
      }
      this.locationBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.NetPoint.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.NetPoint.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public de.dwi.demo.avro.model.Location getLocation() {
      return location;
    }

    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.NetPoint.Builder setLocation(de.dwi.demo.avro.model.Location value) {
      validate(fields()[1], value);
      this.locationBuilder = null;
      this.location = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'location' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public de.dwi.demo.avro.model.Location.Builder getLocationBuilder() {
      if (locationBuilder == null) {
        if (hasLocation()) {
          setLocationBuilder(de.dwi.demo.avro.model.Location.newBuilder(location));
        } else {
          setLocationBuilder(de.dwi.demo.avro.model.Location.newBuilder());
        }
      }
      return locationBuilder;
    }

    /**
     * Sets the Builder instance for the 'location' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public de.dwi.demo.avro.model.NetPoint.Builder setLocationBuilder(de.dwi.demo.avro.model.Location.Builder value) {
      clearLocation();
      locationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'location' field has an active Builder instance
     * @return True if the 'location' field has an active Builder instance
     */
    public boolean hasLocationBuilder() {
      return locationBuilder != null;
    }

    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.NetPoint.Builder clearLocation() {
      location = null;
      locationBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NetPoint build() {
      try {
        NetPoint record = new NetPoint();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        if (locationBuilder != null) {
          record.location = this.locationBuilder.build();
        } else {
          record.location = fieldSetFlags()[1] ? this.location : (de.dwi.demo.avro.model.Location) defaultValue(fields()[1]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NetPoint>
    WRITER$ = (org.apache.avro.io.DatumWriter<NetPoint>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NetPoint>
    READER$ = (org.apache.avro.io.DatumReader<NetPoint>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
