/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dwi.demo.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class StopArea extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2515268798504948109L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StopArea\",\"namespace\":\"de.dwi.demo.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"StopAreaType\",\"symbols\":[\"A\",\"B\"]}},{\"name\":\"points\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"NetPoint\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"location\",\"type\":{\"type\":\"record\",\"name\":\"Location\",\"fields\":[{\"name\":\"gpsX\",\"type\":\"long\"},{\"name\":\"gpsY\",\"type\":\"long\"}]}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StopArea> ENCODER =
      new BinaryMessageEncoder<StopArea>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StopArea> DECODER =
      new BinaryMessageDecoder<StopArea>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<StopArea> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<StopArea> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StopArea>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this StopArea to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a StopArea from a ByteBuffer. */
  public static StopArea fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String id;
  @Deprecated public de.dwi.demo.avro.model.StopAreaType type;
  @Deprecated public java.util.List<de.dwi.demo.avro.model.NetPoint> points;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StopArea() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param type The new value for type
   * @param points The new value for points
   */
  public StopArea(java.lang.String id, de.dwi.demo.avro.model.StopAreaType type, java.util.List<de.dwi.demo.avro.model.NetPoint> points) {
    this.id = id;
    this.type = type;
    this.points = points;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return type;
    case 2: return points;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: type = (de.dwi.demo.avro.model.StopAreaType)value$; break;
    case 2: points = (java.util.List<de.dwi.demo.avro.model.NetPoint>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public de.dwi.demo.avro.model.StopAreaType getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(de.dwi.demo.avro.model.StopAreaType value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'points' field.
   * @return The value of the 'points' field.
   */
  public java.util.List<de.dwi.demo.avro.model.NetPoint> getPoints() {
    return points;
  }

  /**
   * Sets the value of the 'points' field.
   * @param value the value to set.
   */
  public void setPoints(java.util.List<de.dwi.demo.avro.model.NetPoint> value) {
    this.points = value;
  }

  /**
   * Creates a new StopArea RecordBuilder.
   * @return A new StopArea RecordBuilder
   */
  public static de.dwi.demo.avro.model.StopArea.Builder newBuilder() {
    return new de.dwi.demo.avro.model.StopArea.Builder();
  }

  /**
   * Creates a new StopArea RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StopArea RecordBuilder
   */
  public static de.dwi.demo.avro.model.StopArea.Builder newBuilder(de.dwi.demo.avro.model.StopArea.Builder other) {
    return new de.dwi.demo.avro.model.StopArea.Builder(other);
  }

  /**
   * Creates a new StopArea RecordBuilder by copying an existing StopArea instance.
   * @param other The existing instance to copy.
   * @return A new StopArea RecordBuilder
   */
  public static de.dwi.demo.avro.model.StopArea.Builder newBuilder(de.dwi.demo.avro.model.StopArea other) {
    return new de.dwi.demo.avro.model.StopArea.Builder(other);
  }

  /**
   * RecordBuilder for StopArea instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StopArea>
    implements org.apache.avro.data.RecordBuilder<StopArea> {

    private java.lang.String id;
    private de.dwi.demo.avro.model.StopAreaType type;
    private java.util.List<de.dwi.demo.avro.model.NetPoint> points;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.dwi.demo.avro.model.StopArea.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.points)) {
        this.points = data().deepCopy(fields()[2].schema(), other.points);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing StopArea instance
     * @param other The existing instance to copy.
     */
    private Builder(de.dwi.demo.avro.model.StopArea other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.points)) {
        this.points = data().deepCopy(fields()[2].schema(), other.points);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.StopArea.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.StopArea.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public de.dwi.demo.avro.model.StopAreaType getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.StopArea.Builder setType(de.dwi.demo.avro.model.StopAreaType value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.StopArea.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'points' field.
      * @return The value.
      */
    public java.util.List<de.dwi.demo.avro.model.NetPoint> getPoints() {
      return points;
    }

    /**
      * Sets the value of the 'points' field.
      * @param value The value of 'points'.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.StopArea.Builder setPoints(java.util.List<de.dwi.demo.avro.model.NetPoint> value) {
      validate(fields()[2], value);
      this.points = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'points' field has been set.
      * @return True if the 'points' field has been set, false otherwise.
      */
    public boolean hasPoints() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'points' field.
      * @return This builder.
      */
    public de.dwi.demo.avro.model.StopArea.Builder clearPoints() {
      points = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StopArea build() {
      try {
        StopArea record = new StopArea();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (de.dwi.demo.avro.model.StopAreaType) defaultValue(fields()[1]);
        record.points = fieldSetFlags()[2] ? this.points : (java.util.List<de.dwi.demo.avro.model.NetPoint>) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StopArea>
    WRITER$ = (org.apache.avro.io.DatumWriter<StopArea>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StopArea>
    READER$ = (org.apache.avro.io.DatumReader<StopArea>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
