/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dwi.demo.avro.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum StopAreaType {
  A, B  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"StopAreaType\",\"namespace\":\"de.dwi.demo.avro.model\",\"symbols\":[\"A\",\"B\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
