// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Location.proto

package de.dwi.demo.protobuf.model;

public final class LocationWrapper {
  private LocationWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 gpsX = 1;</code>
     */
    boolean hasGpsX();
    /**
     * <code>required int64 gpsX = 1;</code>
     */
    long getGpsX();

    /**
     * <code>required int64 gpsY = 2;</code>
     */
    boolean hasGpsY();
    /**
     * <code>required int64 gpsY = 2;</code>
     */
    long getGpsY();
  }
  /**
   * Protobuf type {@code demo.Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Location() {
      gpsX_ = 0L;
      gpsY_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gpsX_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gpsY_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.dwi.demo.protobuf.model.LocationWrapper.internal_static_demo_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.dwi.demo.protobuf.model.LocationWrapper.internal_static_demo_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.dwi.demo.protobuf.model.LocationWrapper.Location.class, de.dwi.demo.protobuf.model.LocationWrapper.Location.Builder.class);
    }

    private int bitField0_;
    public static final int GPSX_FIELD_NUMBER = 1;
    private long gpsX_;
    /**
     * <code>required int64 gpsX = 1;</code>
     */
    public boolean hasGpsX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 gpsX = 1;</code>
     */
    public long getGpsX() {
      return gpsX_;
    }

    public static final int GPSY_FIELD_NUMBER = 2;
    private long gpsY_;
    /**
     * <code>required int64 gpsY = 2;</code>
     */
    public boolean hasGpsY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 gpsY = 2;</code>
     */
    public long getGpsY() {
      return gpsY_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasGpsX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGpsY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, gpsX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, gpsY_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, gpsX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, gpsY_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.dwi.demo.protobuf.model.LocationWrapper.Location)) {
        return super.equals(obj);
      }
      de.dwi.demo.protobuf.model.LocationWrapper.Location other = (de.dwi.demo.protobuf.model.LocationWrapper.Location) obj;

      boolean result = true;
      result = result && (hasGpsX() == other.hasGpsX());
      if (hasGpsX()) {
        result = result && (getGpsX()
            == other.getGpsX());
      }
      result = result && (hasGpsY() == other.hasGpsY());
      if (hasGpsY()) {
        result = result && (getGpsY()
            == other.getGpsY());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGpsX()) {
        hash = (37 * hash) + GPSX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getGpsX());
      }
      if (hasGpsY()) {
        hash = (37 * hash) + GPSY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getGpsY());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.dwi.demo.protobuf.model.LocationWrapper.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.dwi.demo.protobuf.model.LocationWrapper.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Location)
        de.dwi.demo.protobuf.model.LocationWrapper.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.dwi.demo.protobuf.model.LocationWrapper.internal_static_demo_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.dwi.demo.protobuf.model.LocationWrapper.internal_static_demo_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.dwi.demo.protobuf.model.LocationWrapper.Location.class, de.dwi.demo.protobuf.model.LocationWrapper.Location.Builder.class);
      }

      // Construct using de.dwi.demo.protobuf.model.LocationWrapper.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        gpsX_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        gpsY_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.dwi.demo.protobuf.model.LocationWrapper.internal_static_demo_Location_descriptor;
      }

      public de.dwi.demo.protobuf.model.LocationWrapper.Location getDefaultInstanceForType() {
        return de.dwi.demo.protobuf.model.LocationWrapper.Location.getDefaultInstance();
      }

      public de.dwi.demo.protobuf.model.LocationWrapper.Location build() {
        de.dwi.demo.protobuf.model.LocationWrapper.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.dwi.demo.protobuf.model.LocationWrapper.Location buildPartial() {
        de.dwi.demo.protobuf.model.LocationWrapper.Location result = new de.dwi.demo.protobuf.model.LocationWrapper.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gpsX_ = gpsX_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gpsY_ = gpsY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.dwi.demo.protobuf.model.LocationWrapper.Location) {
          return mergeFrom((de.dwi.demo.protobuf.model.LocationWrapper.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.dwi.demo.protobuf.model.LocationWrapper.Location other) {
        if (other == de.dwi.demo.protobuf.model.LocationWrapper.Location.getDefaultInstance()) return this;
        if (other.hasGpsX()) {
          setGpsX(other.getGpsX());
        }
        if (other.hasGpsY()) {
          setGpsY(other.getGpsY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGpsX()) {
          return false;
        }
        if (!hasGpsY()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.dwi.demo.protobuf.model.LocationWrapper.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.dwi.demo.protobuf.model.LocationWrapper.Location) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long gpsX_ ;
      /**
       * <code>required int64 gpsX = 1;</code>
       */
      public boolean hasGpsX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 gpsX = 1;</code>
       */
      public long getGpsX() {
        return gpsX_;
      }
      /**
       * <code>required int64 gpsX = 1;</code>
       */
      public Builder setGpsX(long value) {
        bitField0_ |= 0x00000001;
        gpsX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 gpsX = 1;</code>
       */
      public Builder clearGpsX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gpsX_ = 0L;
        onChanged();
        return this;
      }

      private long gpsY_ ;
      /**
       * <code>required int64 gpsY = 2;</code>
       */
      public boolean hasGpsY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 gpsY = 2;</code>
       */
      public long getGpsY() {
        return gpsY_;
      }
      /**
       * <code>required int64 gpsY = 2;</code>
       */
      public Builder setGpsY(long value) {
        bitField0_ |= 0x00000002;
        gpsY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 gpsY = 2;</code>
       */
      public Builder clearGpsY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gpsY_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Location)
    }

    // @@protoc_insertion_point(class_scope:demo.Location)
    private static final de.dwi.demo.protobuf.model.LocationWrapper.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.dwi.demo.protobuf.model.LocationWrapper.Location();
    }

    public static de.dwi.demo.protobuf.model.LocationWrapper.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    public de.dwi.demo.protobuf.model.LocationWrapper.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Location.proto\022\004demo\"&\n\010Location\022\014\n\004gp" +
      "sX\030\001 \002(\003\022\014\n\004gpsY\030\002 \002(\003B-\n\032de.dwi.demo.pr" +
      "otobuf.modelB\017LocationWrapper"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_Location_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Location_descriptor,
        new java.lang.String[] { "GpsX", "GpsY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
