// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StopArea.proto

package de.dwi.demo.protobuf.model;

public final class StopAreaWrapper {
  private StopAreaWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StopAreaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.StopArea)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required .demo.StopArea.StopAreaType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .demo.StopArea.StopAreaType type = 2;</code>
     */
    de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType getType();

    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    java.util.List<de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint> 
        getPointList();
    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint getPoint(int index);
    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    int getPointCount();
    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    java.util.List<? extends de.dwi.demo.protobuf.model.NetPointWrapper.NetPointOrBuilder> 
        getPointOrBuilderList();
    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    de.dwi.demo.protobuf.model.NetPointWrapper.NetPointOrBuilder getPointOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code demo.StopArea}
   */
  public  static final class StopArea extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.StopArea)
      StopAreaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StopArea.newBuilder() to construct.
    private StopArea(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StopArea() {
      id_ = "";
      type_ = 0;
      point_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StopArea(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType value = de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = rawValue;
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                point_ = new java.util.ArrayList<de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint>();
                mutable_bitField0_ |= 0x00000004;
              }
              point_.add(
                  input.readMessage(de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          point_ = java.util.Collections.unmodifiableList(point_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.dwi.demo.protobuf.model.StopAreaWrapper.internal_static_demo_StopArea_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.dwi.demo.protobuf.model.StopAreaWrapper.internal_static_demo_StopArea_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.class, de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.Builder.class);
    }

    /**
     * Protobuf enum {@code demo.StopArea.StopAreaType}
     */
    public enum StopAreaType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>A = 0;</code>
       */
      A(0),
      /**
       * <code>B = 1;</code>
       */
      B(1),
      ;

      /**
       * <code>A = 0;</code>
       */
      public static final int A_VALUE = 0;
      /**
       * <code>B = 1;</code>
       */
      public static final int B_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static StopAreaType valueOf(int value) {
        return forNumber(value);
      }

      public static StopAreaType forNumber(int value) {
        switch (value) {
          case 0: return A;
          case 1: return B;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StopAreaType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          StopAreaType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StopAreaType>() {
              public StopAreaType findValueByNumber(int number) {
                return StopAreaType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.getDescriptor().getEnumTypes().get(0);
      }

      private static final StopAreaType[] VALUES = values();

      public static StopAreaType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private StopAreaType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:demo.StopArea.StopAreaType)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required .demo.StopArea.StopAreaType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .demo.StopArea.StopAreaType type = 2;</code>
     */
    public de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType getType() {
      de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType result = de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType.valueOf(type_);
      return result == null ? de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType.A : result;
    }

    public static final int POINT_FIELD_NUMBER = 3;
    private java.util.List<de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint> point_;
    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    public java.util.List<de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint> getPointList() {
      return point_;
    }
    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    public java.util.List<? extends de.dwi.demo.protobuf.model.NetPointWrapper.NetPointOrBuilder> 
        getPointOrBuilderList() {
      return point_;
    }
    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    public int getPointCount() {
      return point_.size();
    }
    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    public de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint getPoint(int index) {
      return point_.get(index);
    }
    /**
     * <code>repeated .demo.NetPoint point = 3;</code>
     */
    public de.dwi.demo.protobuf.model.NetPointWrapper.NetPointOrBuilder getPointOrBuilder(
        int index) {
      return point_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPointCount(); i++) {
        if (!getPoint(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_);
      }
      for (int i = 0; i < point_.size(); i++) {
        output.writeMessage(3, point_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      for (int i = 0; i < point_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, point_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea)) {
        return super.equals(obj);
      }
      de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea other = (de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && getPointList()
          .equals(other.getPointList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (getPointCount() > 0) {
        hash = (37 * hash) + POINT_FIELD_NUMBER;
        hash = (53 * hash) + getPointList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.StopArea}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.StopArea)
        de.dwi.demo.protobuf.model.StopAreaWrapper.StopAreaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.dwi.demo.protobuf.model.StopAreaWrapper.internal_static_demo_StopArea_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.dwi.demo.protobuf.model.StopAreaWrapper.internal_static_demo_StopArea_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.class, de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.Builder.class);
      }

      // Construct using de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPointFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          pointBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.dwi.demo.protobuf.model.StopAreaWrapper.internal_static_demo_StopArea_descriptor;
      }

      public de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea getDefaultInstanceForType() {
        return de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.getDefaultInstance();
      }

      public de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea build() {
        de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea buildPartial() {
        de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea result = new de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (pointBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            point_ = java.util.Collections.unmodifiableList(point_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.point_ = point_;
        } else {
          result.point_ = pointBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea) {
          return mergeFrom((de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea other) {
        if (other == de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (pointBuilder_ == null) {
          if (!other.point_.isEmpty()) {
            if (point_.isEmpty()) {
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePointIsMutable();
              point_.addAll(other.point_);
            }
            onChanged();
          }
        } else {
          if (!other.point_.isEmpty()) {
            if (pointBuilder_.isEmpty()) {
              pointBuilder_.dispose();
              pointBuilder_ = null;
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000004);
              pointBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPointFieldBuilder() : null;
            } else {
              pointBuilder_.addAllMessages(other.point_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        for (int i = 0; i < getPointCount(); i++) {
          if (!getPoint(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>required .demo.StopArea.StopAreaType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .demo.StopArea.StopAreaType type = 2;</code>
       */
      public de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType getType() {
        de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType result = de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType.valueOf(type_);
        return result == null ? de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType.A : result;
      }
      /**
       * <code>required .demo.StopArea.StopAreaType type = 2;</code>
       */
      public Builder setType(de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea.StopAreaType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .demo.StopArea.StopAreaType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint> point_ =
        java.util.Collections.emptyList();
      private void ensurePointIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          point_ = new java.util.ArrayList<de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint>(point_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint, de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder, de.dwi.demo.protobuf.model.NetPointWrapper.NetPointOrBuilder> pointBuilder_;

      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public java.util.List<de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint> getPointList() {
        if (pointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(point_);
        } else {
          return pointBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public int getPointCount() {
        if (pointBuilder_ == null) {
          return point_.size();
        } else {
          return pointBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint getPoint(int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);
        } else {
          return pointBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public Builder setPoint(
          int index, de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.set(index, value);
          onChanged();
        } else {
          pointBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public Builder setPoint(
          int index, de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public Builder addPoint(de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(value);
          onChanged();
        } else {
          pointBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public Builder addPoint(
          int index, de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(index, value);
          onChanged();
        } else {
          pointBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public Builder addPoint(
          de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public Builder addPoint(
          int index, de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public Builder addAllPoint(
          java.lang.Iterable<? extends de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint> values) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, point_);
          onChanged();
        } else {
          pointBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public Builder clearPoint() {
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          pointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public Builder removePoint(int index) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.remove(index);
          onChanged();
        } else {
          pointBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder getPointBuilder(
          int index) {
        return getPointFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public de.dwi.demo.protobuf.model.NetPointWrapper.NetPointOrBuilder getPointOrBuilder(
          int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);  } else {
          return pointBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public java.util.List<? extends de.dwi.demo.protobuf.model.NetPointWrapper.NetPointOrBuilder> 
           getPointOrBuilderList() {
        if (pointBuilder_ != null) {
          return pointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(point_);
        }
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder addPointBuilder() {
        return getPointFieldBuilder().addBuilder(
            de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder addPointBuilder(
          int index) {
        return getPointFieldBuilder().addBuilder(
            index, de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.NetPoint point = 3;</code>
       */
      public java.util.List<de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder> 
           getPointBuilderList() {
        return getPointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint, de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder, de.dwi.demo.protobuf.model.NetPointWrapper.NetPointOrBuilder> 
          getPointFieldBuilder() {
        if (pointBuilder_ == null) {
          pointBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint, de.dwi.demo.protobuf.model.NetPointWrapper.NetPoint.Builder, de.dwi.demo.protobuf.model.NetPointWrapper.NetPointOrBuilder>(
                  point_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          point_ = null;
        }
        return pointBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.StopArea)
    }

    // @@protoc_insertion_point(class_scope:demo.StopArea)
    private static final de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea();
    }

    public static de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<StopArea>
        PARSER = new com.google.protobuf.AbstractParser<StopArea>() {
      public StopArea parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StopArea(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StopArea> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopArea> getParserForType() {
      return PARSER;
    }

    public de.dwi.demo.protobuf.model.StopAreaWrapper.StopArea getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_StopArea_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_StopArea_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016StopArea.proto\022\004demo\032\016NetPoint.proto\"~" +
      "\n\010StopArea\022\n\n\002id\030\001 \002(\t\022)\n\004type\030\002 \002(\0162\033.d" +
      "emo.StopArea.StopAreaType\022\035\n\005point\030\003 \003(\013" +
      "2\016.demo.NetPoint\"\034\n\014StopAreaType\022\005\n\001A\020\000\022" +
      "\005\n\001B\020\001B-\n\032de.dwi.demo.protobuf.modelB\017St" +
      "opAreaWrapper"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.dwi.demo.protobuf.model.NetPointWrapper.getDescriptor(),
        }, assigner);
    internal_static_demo_StopArea_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_StopArea_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_StopArea_descriptor,
        new java.lang.String[] { "Id", "Type", "Point", });
    de.dwi.demo.protobuf.model.NetPointWrapper.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
