/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.dwi.demo.thrift.model;


public enum StopAreaType implements org.apache.thrift.TEnum {
  A(1),
  B(2);

  private final int value;

  private StopAreaType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static StopAreaType findByValue(int value) { 
    switch (value) {
      case 1:
        return A;
      case 2:
        return B;
      default:
        return null;
    }
  }
}
